[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
dist-name = "tfr_alert"
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["README.md", "LICENSE.md"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

# for now just linux / windows
[[dist.bin]]
name = "tfr_app"
path = "app"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu"
]

[[dist.bin]]
name = "tfr_bot"
path = "bot"
targets = ["x86_64-unknown-linux-gnu"]
