name: CI

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4.1.1
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          persist-credentials: false
      # dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
      # (rust-toolchain@v1 latest reviewed and pinned)
      - uses: dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
        with:
          toolchain: stable
      # Swatinem/rust-cache@v2.8.0
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      # dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
      - run: cargo check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@4.1.1
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          persist-credentials: false
      # dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
      - uses: dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
        with:
          toolchain: stable
          components: rustfmt
      # Swatinem/rust-cache@v2.8.0
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      # dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
      - run: cargo fmt --all --check

  build_wasm:
    name: build
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@4.1.1
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          persist-credentials: false
      # dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
      - uses: dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
        with:
          toolchain: stable
          targets: stable-x86_64-unknown-linux-gnu
      # Swatinem/rust-cache@v2.8.0
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      # dtolnay/rust-toolchain@30dc51db75d080812bc4a28ba3f342840b2e7dd7
      - run: cargo build